import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='flex items-center justify-center '>
        <h1 className="text-lg text-sky-400">
          Welcome to <a href="https://nextjs.org">Next.js xd!</a>
        </h1>
      </main>

    </div>
  )
}
